export type OrderCategory = "lab" | "imaging" | "ecg" | "bedside";

export type Orderable = {
  id: string;
  name: string;
  category: OrderCategory;
  /** Minutes until the result comes back. Shown to the user as a cost of ordering. */
  turnaroundMin: number;
  costUsd: number;
  /** Pre-authored result. Never generated by the model. */
  result: string;
  abnormal?: boolean;
};

export type Vitals = {
  hr: string;
  bp: string;
  rr: string;
  temp: string;
  spo2: string;
};

export type RubricItem = {
  id: string;
  label: string;
  /** Why this matters — surfaced in the debrief when the student misses it. */
  why: string;
};

export type Case = {
  id: string;
  /** Shown in the case list. Must not leak the diagnosis. */
  title: string;
  chiefComplaint: string;
  difficulty: "intro" | "core" | "hard";
  specialty: string;
  patient: {
    name: string;
    age: number;
    gender: string;
    /** Voice, temperament, how forthcoming they are. Drives the roleplay. */
    persona: string;
    /**
     * A relative or carer at the bedside who answers when the patient can't.
     * Present on cases where taking a collateral history is the skill being tested.
     */
    collateral?: {
      name: string;
      relationship: string;
      persona: string;
    };
    vitals: Vitals;
  };
  /** Everything the model knows and the student does not. Never sent to the client. */
  hidden: {
    diagnosis: string;
    narrative: string;
    history: string;
    examFindings: Record<string, string>;
  };
  orderables: Orderable[];
  rubric: {
    mustAsk: RubricItem[];
    mustOrder: string[];
    shouldNotOrder: string[];
    redFlags: RubricItem[];
    correctDiagnosis: string;
    acceptableDifferential: string[];
    keyManagement: string[];
  };
};

/** The case minus everything that would give the answer away. */
export type PublicCase = {
  id: string;
  title: string;
  chiefComplaint: string;
  difficulty: Case["difficulty"];
  specialty: string;
  patient: Omit<Case["patient"], "persona" | "collateral"> & {
    collateral?: { name: string; relationship: string };
  };
  orderables: Array<Omit<Orderable, "result" | "abnormal">>;
};

export function toPublicCase(c: Case): PublicCase {
  return {
    id: c.id,
    title: c.title,
    chiefComplaint: c.chiefComplaint,
    difficulty: c.difficulty,
    specialty: c.specialty,
    patient: {
      name: c.patient.name,
      age: c.patient.age,
      gender: c.patient.gender,
      vitals: c.patient.vitals,
      ...(c.patient.collateral && {
        collateral: {
          name: c.patient.collateral.name,
          relationship: c.patient.collateral.relationship,
        },
      }),
    },
    orderables: c.orderables.map(({ id, name, category, turnaroundMin, costUsd }) => ({
      id,
      name,
      category,
      turnaroundMin,
      costUsd,
    })),
  };
}
